global:
  scrape_interval:     15s
  external_labels:
    monitor: 'sysdig-prometheus'
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'pushgateway'
        scrape_interval: 5s
        static_configs:
          - targets: ['pushgateway-service:9091']

